name: deploiement en continue du carte

on:
  push:
    branches:
      - main


jobs:
  deploy:

    runs-on: ubuntu-latest
  

    steps:

    - name : deploiement 
      run : docker push mkhatiri/carte:v1

    - name: run 
      run: docker run carte