name: deploiement en continue du carte

on:
  push:
    branches:
      - main

concurrency: main-promotion-pipeline



jobs:
  compiler:

    runs-on: ubuntu-latest
  

    steps:

    - name : deploiement 
      run : echo "deploy"