name: intgration en continue du carte

on:
  pull_request:
    
  

jobs:
  compiler:

    runs-on: ubuntu-latest
  

    steps:
    - uses: actions/checkout@v3

    - name : build
      run : docker build -t carte .

    - name: tester
      run: |
        docker image ls
        docker run carte

    - name: docker login
      run: 
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

    - name: tag
      run: docker tag carte ${{ secrets.DOCKER_USERNAME }}/carte:$(date +%s)
    - name: push
      run : docker push ${{ secrets.DOCKER_USERNAME }}/carte