name: intgration en continue du carte

on:
  push:
    branches:
      - main
  

jobs:
  compiler:

    runs-on: ubuntu-latest
  

    steps:
    - name : step1
      run : echo "quelque chose a changé"
